---
kind: Service
apiVersion: v1
metadata:
  name: juice-shop
spec:
  type: NodePort
  selector:
    app: juice-shop
  ports:
  - name: http
    nodePort: 30080
    port: 3000
    targetPort: 3000
    protocol: TCP
